/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidades.Localizaciones;
import java.awt.Point;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author luis
 */
public class FormModificarLocalizacion extends javax.swing.JFrame {

    static FormGESLocalizaciones padre;
    static Localizaciones localizacion;

    /**
     * Creates new form FormNuevaLocalizacion
     */
    public FormModificarLocalizacion(FormGESLocalizaciones fpadre, Localizaciones l) {
        initComponents();
        this.padre = fpadre;
        this.localizacion = l;
        this.jTextFieldLatitud.setText("" + l.getGradosLatitud());
        this.jTextFieldLoNgitud.setText("" + l.getGradosLongitud());
        if (l.getLatitud().equals('s') || l.getLatitud().equals('S')) {
            this.jRadioButtonSur.setSelected(true);
            this.jRadioButtonNorte.setSelected(false);
        } else {
            this.jRadioButtonNorte.setSelected(true);
            this.jRadioButtonSur.setSelected(false);
        }
        if (l.getLongitud().equals('e') || l.getLongitud().equals('E')) {
            this.jRadioButtonEste.setSelected(true);
            this.jRadioButtonOeste.setSelected(false);
        } else {
            this.jRadioButtonOeste.setSelected(true);
            this.jRadioButtonEste.setSelected(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLatitud = new javax.swing.ButtonGroup();
        buttonGroupLoNgitud = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonResetearCampos = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jPanelLogitud = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLoNgitud = new javax.swing.JTextField();
        jRadioButtonEste = new javax.swing.JRadioButton();
        jRadioButtonOeste = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLatitud = new javax.swing.JTextField();
        jRadioButtonNorte = new javax.swing.JRadioButton();
        jRadioButtonSur = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Localización");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Localización");

        jButtonResetearCampos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonResetearCampos.setText("Borrar campos");
        jButtonResetearCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetearCamposActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jPanelLogitud.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 204, 0)));
        jPanelLogitud.setToolTipText("La longitud es un ángulo imaginario determinado por el Meridiano de Greenwich o Meridiano 0, que divide el mundo en dos regiones, la occidental (Oeste) y la oriental (Este).   \n");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Longitud:");
        jLabel2.setToolTipText("");

        jTextFieldLoNgitud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldLoNgitud.setText("XX.XX");
        jTextFieldLoNgitud.setToolTipText("Introduzca la longitud en grados en formato decimal. Ej: ±xxx,xx");

        buttonGroupLoNgitud.add(jRadioButtonEste);
        jRadioButtonEste.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButtonEste.setText("Este");
        jRadioButtonEste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEsteActionPerformed(evt);
            }
        });

        buttonGroupLoNgitud.add(jRadioButtonOeste);
        jRadioButtonOeste.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButtonOeste.setText("Oeste");

        javax.swing.GroupLayout jPanelLogitudLayout = new javax.swing.GroupLayout(jPanelLogitud);
        jPanelLogitud.setLayout(jPanelLogitudLayout);
        jPanelLogitudLayout.setHorizontalGroup(
            jPanelLogitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogitudLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldLoNgitud, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLogitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonEste)
                    .addComponent(jRadioButtonOeste))
                .addGap(14, 14, 14))
        );
        jPanelLogitudLayout.setVerticalGroup(
            jPanelLogitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogitudLayout.createSequentialGroup()
                .addGroup(jPanelLogitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLogitudLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonEste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonOeste))
                    .addGroup(jPanelLogitudLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelLogitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLoNgitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 204, 51)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Latitud:");
        jLabel3.setToolTipText("La latitud es el ángulo imaginario que un punto ocupa respecto del ecuador (la línea imaginaria que divide el mundo en dos hemisferios: Norte y Sur)\n\n\n");

        jTextFieldLatitud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldLatitud.setText("XX.XX");
        jTextFieldLatitud.setToolTipText("Introduzca la latitud en grados en formato decimal. Ej: ±xxx,xx");
        jTextFieldLatitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLatitudActionPerformed(evt);
            }
        });

        buttonGroupLatitud.add(jRadioButtonNorte);
        jRadioButtonNorte.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButtonNorte.setText("Norte");

        buttonGroupLatitud.add(jRadioButtonSur);
        jRadioButtonSur.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButtonSur.setText("Sur");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonNorte)
                    .addComponent(jRadioButtonSur))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonNorte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSur)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonResetearCampos)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanelLogitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLogitud, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButtonResetearCampos)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonVolver))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.padre.getJTable().repaint();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        boolean ok = true;
        String msj = "";
        if (this.jTextFieldLatitud.getText().isEmpty()) {
            ok = false;
            msj += "\nLa longitud es obligatoria.";
        }
        if (!this.jRadioButtonEste.isSelected() && !this.jRadioButtonOeste.isSelected()) {
            ok = false;
            msj += "\nEs obligatorio marcar la longitud ESTE u OESTE.";
        }
        if (this.jTextFieldLatitud.getText().isEmpty()) {
            ok = false;
            msj += "\nLa latitud es obligatoria.";
        }
        if (!this.jRadioButtonNorte.isSelected() && !this.jRadioButtonSur.isSelected()) {
            ok = false;
            msj += "\nEs obligatorio marcar la latitud NORTE o SUR.";
        }
        if (!ok) {
            JOptionPane.showMessageDialog(this, "Debe solucionar los siguientes problemas:\n" + msj, "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            msj = "\n" + this.jTextFieldLoNgitud.getText() + "º Longitud " + (this.jRadioButtonNorte.isSelected() ? "NORTE" : "SUR");
            msj += "\n" + this.jTextFieldLatitud.getText() + "º Latitud " + (this.jRadioButtonEste.isSelected() ? "ESTE" : "OESTE");
            Object[] opciones = {"Sí", "No"};
            int i = JOptionPane.showOptionDialog(this, "¿Son los datos modificados de la Localización correctos?\n" + msj, "Modificar Localización", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
            if (i == JOptionPane.NO_OPTION) {
                return;
            }

            try {
                char longitud, latitud;
                longitud = this.jRadioButtonEste.isSelected() ? 'E' : 'O';
                latitud = this.jRadioButtonNorte.isSelected() ? 'N' : 'S';
                float gradosLongitud, gradosLatitud;
                gradosLongitud = Float.valueOf(this.jTextFieldLoNgitud.getText());
                gradosLatitud = Float.valueOf(this.jTextFieldLatitud.getText());
                localizacion.setLongitud(longitud);
                localizacion.setLatitud(latitud);
                localizacion.setGradosLatitud(gradosLatitud);
                localizacion.setGradosLongitud(gradosLongitud);
                javax.persistence.EntityManager entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("bdinvernadero?zeroDateTimeBehavior=convertToNullPU").createEntityManager();

                entityManager0.getTransaction().begin();
                entityManager0.merge(localizacion);

                entityManager0.getTransaction().commit();
                JOptionPane.showMessageDialog(this, "Se ha modificado correctamente la Localización.");

                Point location = this.padre.getLocation();
                this.padre = new FormGESLocalizaciones();
                this.padre.setLocation(location);
                this.padre.setVisible(true);
                this.dispose();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERROR al añadir la Localización.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jRadioButtonEsteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEsteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEsteActionPerformed

    private void jTextFieldLatitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLatitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLatitudActionPerformed

    private void jButtonResetearCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetearCamposActionPerformed
        if (this.jRadioButtonEste.isSelected()) {
            this.jRadioButtonEste.setSelected(false);
        }
        if (this.jRadioButtonOeste.isSelected()) {
            this.jRadioButtonOeste.setSelected(false);
        }
        if (this.jRadioButtonNorte.isSelected()) {
            this.jRadioButtonNorte.setSelected(false);
        }
        if (this.jRadioButtonSur.isSelected()) {
            this.jRadioButtonSur.setSelected(false);
        }
        this.jTextFieldLoNgitud.setText("XX.XX");
        this.jTextFieldLatitud.setText("XX.XX");
    }//GEN-LAST:event_jButtonResetearCamposActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormModificarLocalizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormModificarLocalizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormModificarLocalizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormModificarLocalizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormModificarLocalizacion(padre, localizacion).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLatitud;
    private javax.swing.ButtonGroup buttonGroupLoNgitud;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonResetearCampos;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelLogitud;
    private javax.swing.JRadioButton jRadioButtonEste;
    private javax.swing.JRadioButton jRadioButtonNorte;
    private javax.swing.JRadioButton jRadioButtonOeste;
    private javax.swing.JRadioButton jRadioButtonSur;
    private javax.swing.JTextField jTextFieldLatitud;
    private javax.swing.JTextField jTextFieldLoNgitud;
    // End of variables declaration//GEN-END:variables
}
